[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "Clishortener"
version = "0.3.1"
description = "A lightweight, feature-rich CLI tool to shorten links using 12+ services—with zero configuration required."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
keywords = ["url shortener", "cli tool", ]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "Environment :: Console",
    "Topic :: Utilities"
]
dependencies = [
    "requests>=2.28.0",
]
[project.optional-dependencies]
rich = ["rich"]
argcomplete = ["argcomplete"]
pysocks = ["PySocks"]
keyring = ["keyring"]
keyringalt = ["keyrings.alt"]
qrcode = ["qrcode"]
full = ["rich", "argcomplete", "requests[socks]", "keyring", "qrcode"]

[project.urls]
Homepage = "https://github.com/Ruizennis/Clishortener"
Issues = "https://github.com/Ruizennis/Clishortener/issues"

[project.scripts]
cshorten = "Clishortener:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["Clishortener*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
Clishortener = ["*.json", "modules/*.py", "required/*.py"]
